spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopin_db
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
application:
  security:
    permittedEndpoints: /**
